name: Compilar servidores com Clang no macOS
# build_servers_cmake_osx.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre acione todas as ações do GitHub se uma ação ou algo relacionado à CI for alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve ser executado quando um arquivo em um diretório de código-fonte for modificado.
      - 'src/**'
      - '3rdparty/**'
      # Este workflow deve ser executado sempre que um arquivo relacionado ao CMake for modificado
      - '**/CMakeLists.txt'

jobs:
  build:
    # O GitHub Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]' ou '[actions skip]', mas não versões com hífen.
    # É uma verificação geral caso um Pull Request seja aberto e alguém esteja no modo automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # O rótulo macos-latest atualmente aponta para macos-14.
          # O rótulo YAML macos-latest usará macos-15 em agosto de 2025
          os: [macos-14, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Atualizar e instalar pacotes
        # Os runners macOS já possuem a maioria dos pacotes que o rAthena requer para compilar.
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
        run: |
          brew update
          brew install pcre
          brew install mysql
          brew install mysql-client

      # Instalar a versão mais recente do CMake.
      - uses: lukka/get-cmake@latest

      - name: Criar diretório de build
        run: mkdir cbuild

      - name: Gerar Makefiles Unix
        run: |
          cd cbuild
          cmake ..

      - name: Comando - make
        run: |
          cd cbuild
          make
